src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from posts import views
from contact import views

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^', include("contact.urls", namespace = 'home')),
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace = 'comments')),
    url(r'^contact/', include("contact.urls", namespace = 'contact')),
    #url('^markdown/', include( 'django_markdown.urls')),
    url(r'^posts/', include("posts.urls", namespace = 'posts')),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/contact/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
  home_page,
  about_page,
  contact_form,
  contact_thanks,
  contact_join,
  contact_jointhanks,
  contact_unsubscribe,
  )

urlpatterns = [
    url(r'^form/$', contact_form, name='contact'),
    url(r'^about/$', about_page, name='about'),
    url(r'^thanks/$', contact_thanks, name='cthanks'),
    url(r'^subscribe/$', contact_join, name='join'),
    url(r'^subscribe/thanks/$', contact_jointhanks, name='thanks'),
    url(r'^unsubscribe/success/$', contact_unsubscribe, name='unsubscribe'),
    url(r'^$', home_page, name='home'),
]

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
  post_list,
  post_create,
  post_detail,
  post_update,
  post_delete,
  )

urlpatterns = [
    
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$',post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

src/contact/models.py
from django.db import models

# Create your models here.


class Join(models.Model):
  email = models.EmailField()
  timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
  updated = models.DateTimeField(auto_now_add=False, auto_now=True)

  def __str__(self):
    return self.email

src/posts/models.py
#### Imports ####
# 1 - Stdlib imports
# 2 - Core Django imports
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
#3  - Third Party Imports
from markdown_deux import markdown
from comments.models import Comment
#4  - Imports from local apps
from .utils import get_read_time
#### end of imports ####

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(published__lte=timezone.now())

def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True,
            width_field='width_field',
            height_field='height_field' )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    published = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0) #models.TimeField(null=True, blank=True)#assume mins
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    #updated - saves and sets time updated
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    #timestamp - saves and sets time created
    objects = PostManager()
  
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})
    # return "/posts/%s/" %(self.id)

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)
    
    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs
    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type
  
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

   
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    
    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

src/contact/forms.py
from django import forms
from .models import Join


class ContactForm(forms.Form):
  first_name = forms.CharField(required=True)
  last_name = forms.CharField(required=True)
  email = forms.EmailField(required=True)
  subject = forms.CharField(required=True)
  message = forms.CharField(required=True, widget=forms.Textarea)
  
#  def __init__(self, *args, **kwargs):
#    super(ContactForm, self).__init__(*args, **kwargs)
#    self.fields['first_name'].label = "Your first name:"
#    self.fields['last_name'].label = "Your last name:"
#    self.fields['email'].label = "Your email:"
#    self.fields['subject'].label = "Your subject:"
#    self.fields['message'].label = "Your message:"
  
  

class EmailForm(forms.Form): #regular django form method
  #name = forms.CharField(required=False)
  email = forms.EmailField()
  
  
class JoinForm(forms.ModelForm): #model form method
  class Meta:
    model = Join
    fields = '__all__'

src/posts/forms.py
# 1 - Stdlib imports
# 2 - Core Django imports
from django import forms
# 3 - Third Party Imports
from pagedown.widgets import PagedownWidget
# 4 - Imports from local app
from .models import Post

class PostForm(forms.ModelForm):
  content = forms.CharField(widget=PagedownWidget(show_preview=False))
  published = forms.DateField(widget=forms.SelectDateWidget)
  class Meta:
    model = Post
    fields = [
      "title",
      "content",
      "image",
      "draft",
      "published",
      ]

src/contact/views.py
from django.shortcuts import render, redirect

from .forms import ContactForm, JoinForm, EmailForm #, JoinForm
from .models import Join

from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.template import Context


def home_page(request):
  context = {
    'nbar':'home'
    }
  return render(request, 'home.html', context)


def about_page(request):
  context = {
    'nbar':'about'
    }
  return render(request, 'about.html', context)



def contact_form(request):
  form_class = ContactForm
  
  if request.method == 'POST':
    form = form_class(data=request.POST)
    
    if form.is_valid():
      first_name = request.POST.get('first_name', '')
      last_name = request.POST.get('last_name', '')
      email = request.POST.get('email', '')
      subject = request.POST.get('subject', '')
      message = request.POST.get('message', '')
      
      
      template = get_template('contact_template.txt')
      
      context = {
        'first_name': first_name,
        'last_name':last_name,
        'email':email,
        'subject':subject,
        'message':message,
      }
      content = template.render(context)
      
      email = EmailMessage(
          "New contact form submission",
          content,
          "www.tristanbowles.co.uk" + '',
          ['tristanbowles@googlemail.com'],
          headers = {'Reply-To': email }
      )
      email.send()
      return redirect('contact:cthanks')


  return render(request, "contact_form.html", {'form': form_class, 'nbar':'contact'})

def contact_thanks(request):
  return render(request, "contact_thanks.html", {'nbar':'contact'})


def contact_join(request):
  
  form = JoinForm(request.POST or None)
  if form.is_valid():
    new_join = form.save(commit=False)
    email = form.cleaned_data['email']
    new_join, created = Join.objects.get_or_create(email=email) #stops duplicate emails being inputted
   # new_join.save() #use this to save if you didnt want to stop duplicates
    return redirect('contact:thanks')
  context = {
    "form": form,
    "nbar": "subscribe"
    }
  return render(request, "join_form.html", context)
  
  
def contact_jointhanks(request):
  context = {
    "nbar": "subscribe"
    }
  return render(request, "join_thanks.html", context)

def contact_unsubscribe(request):
  
#TODO - Add unsubscribe user from mailing list

  context = {
    "nbar": "subscribe"
    }
  return render(request, "join_unsubscribe.html", context)

src/posts/views.py
try:
  from urllib.parse import quote_plus
except:
  pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post


def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    
    if not request.user.is_authenticated():
        raise Http404
    
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        print (form.cleaned_data.get("title"))
        instance.save()
        #message success
        messages.success(request, "Success: blog entry created!")
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        messages.error(request, "Unable to create blog entry!")

    context = {
        "form": form,
        "nbar": "blog"
        }
    return render(request, "post_form.html", context)
  
def post_detail(request,slug=None):
    today = timezone.now().date()
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.published > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id,
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
      
        new_comment, created = Comment.objects.get_or_create(
                                user = request.user,
                                content_type = content_type,
                                object_id = obj_id,
                                content = content_data,
                                parent = parent_obj,
                                )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    
    comments = instance.comments
    context = {
        "title": instance.title,
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "comment_form": form,
        "today": today,
        "nbar": "blog"
        }
    return render(request, "post_detail.html", context)

def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active().order_by("-timestamp") # order_by("-timestamp") #order by most recently created first
    if request.user.is_staff or request.user.is_superuser: #for staff, so they can see drafts
        queryset_list = Post.objects.all().order_by("-timestamp")
  
    #query deals with search function of blog posts. Links with search input in menu bar
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
              ).distinct() #distinct makes sure no duplciate search items
    
    paginator = Paginator(queryset_list, 10) # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset= paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
  
    context = {
        "object_list": queryset,
        "title": "List",
        "page_request_var":page_request_var,
        "today": today,
        "nbar": "blog"
        }
    return render(request, "post_list.html", context)

def post_update(request, slug="None"):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        print (form.cleaned_data.get("title"))
        instance.save()
        #message success
        messages.success(request, "Success: blog entry updated!")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": instance.title,
        "instance": instance,
        "form" : form,
        "nbar": "blog"
        }
    return render(request, "post_form.html", context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Success: blog entry deleted!")
    return redirect("posts:list")

src/templates/about.html
{% extends "base.html" %}

{% block head_title %}About{% endblock %}

{% block content %}

<h1>About</h1>

<p>Tristan has a passion for writing code, developing ideas and working with new technologies.  He is currently devoting his spare time to learning Django and Python.</p>
<p>Please get in touch if you'd like to ask a question or if you'd like to talk about collaborating on future projects.</p>


{% endblock content %}

src/templates/accounts_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Login{% endblock head_title%}

{% block content %}

<div class="row">


  
<div class="col-sm-6">
<h1>{{ title }}</h1>

<hr/>
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
    {{ form|crispy }}
<input type='submit' class= 'btn btn-default' value='{{ title }}' />
</form>
</div>
</div>

{% endblock content %}

src/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}{{ object.content }}{% endblock head_title%}

{% block content %}



<div class="row">
    
<div class="col-md-12">
    <h1>Confirm Delete</h1>

    <form method='POST' action='.'>{% csrf_token %}
    <p>Are you sure you want to delete: "{{ object.content }}"?</p>
    <input type='submit' value='Confirm' class='btn btn-warning'>
    <a href='{{ object.get_absolute_url }}'class='btn btn-default'>Cancel</a>
    </form>
   </div><!--end of comment reply-->
    

</div>


{% endblock content %}

src/templates/contact_thanks.html
{% extends "base.html" %}

{% block head_title %}Thanks{% endblock %}

{% block content %}

<h1>Thank you</h1>

<p>Thanks for submitting your message. I'll be in touch soon.</p>

{% endblock content %}

src/templates/footer_display.html
{% load staticfiles %}

<!--footer-->
    <div id=footer>
            <div class="container">
                <div class="row">
<!--Menu links-->
                    <div class="col-md-3 col-sm-6 col-xs-7">
                        <ul id="footer-menu">
                            <li><a href="{% url 'posts:list' %}">Home</a></li>
                            <li><a href="http://www.tristanbowles.co.uk/about/">About</a></li>
                            <li><a href="http://www.tristanbowles.co.uk/links/">Links</a></li>
                            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                        </ul>
                     </div> <!--Menu links end-->
<!--Social Media Icons-->
                    <div class="col-md-4 col-sm-6 col-xs-5">
                    <ul id="social">
                       <li><a href="https://twitter.com/trisvandis"><img src="{% static 'static_dirs/images/twitter.png' %}"  alt="Tris on Twitter"></a></li>                          <li><a href="https://uk.linkedin.com/in/tristan-bowles-25077323"><img src="{% static 'static_dirs/images/linkedin.png' %}" alt="Tris on Linked In"></a></li>
                    </ul> <!--end social media list-->
                    </div> <!--Social media icons end-->
<!--Site Info-->
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <ul id="sig">
                            <p>&nbsp;</p>
                            <li><p>Site Designed By: Tristan Bowles</p></li>
                            <li><p>Email:<a href="mailto:info@tristanbowles.co.uk">info@tristanbowles.co.uk</a></p></li>
                        </ul>
                   </div> <!--Site Info end-->
                </div> <!--end of row-->
            </div> <!--end of container-->
    </div> <!--end footer-->

src/templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome{% endblock head_title%}

{% block content %}

<div class="row">


  
<div class="col-sm-6">
<h1>Landing Page</h1>

<hr/>

<h3>Welcome to tristanbowles.co.uk!</h3>
<p>Offer goes here</p>


</div>
</div>
{% endblock content %}

src/templates/join_form.html
{% extends "base.html" %}

{% block head_title %}Subscribe{% endblock %}

{% block content %}

<h1>Subscribe</h1>

<form method='POST' action=''>{% csrf_token %}
    {{ form.as_p }}
  <input type='submit' value='Subscribe' class='btn' />
</form>


{% endblock content %}

src/templates/join_thanks.html
{% extends "base.html" %}

{% block head_title %}Thanks{% endblock %}

{% block content %}

<h1>Thank you!</h1>

<p>Thanks for subsrcibing! I'll be in touch soon...</p>


{% endblock content %}

src/templates/join_unsubscribe.html
{% extends "base.html" %}

{% block content %}

<h1>Unsubscription</h1>

<p>Success - You have been removed from the mailing list.</p>


{% endblock content %}

src/templates/jumbotron_display.html
<div class="jumbotron">
  <h1>Tristan Bowles</h1>
  <p>Web Developer</p>
</div><!--end of jumbrotron-->

src/templates/menu_display.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'contact:home' %}" src="{% static 'images/drawing.png' %}" alt="Tris logo" height="20" width="20"></a>
        </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" id="myTab">
                <li class="{% if nbar == 'blog' %}active{% endif %}"><a href="{% url 'posts:list' %}">Blog<span class="sr-only">(current)</span></a>
                </li>
                <li class="{% if nbar == 'about' %}active{% endif %}"><a href="{% url 'contact:about' %}">About</a>
                </li>
                <li class="{% if nbar == 'contact' %}active{% endif %}"><a href="{% url 'contact:contact' %}">Contact</a>
                </li>
            <!--li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Links <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="http://www.tristanbowles.co.uk/links/">Web Development Tools</a></li>
                <li><a href="http://www.tristanbowles.co.uk/links/">Coding Tutorials</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="http://www.tristanbowles.co.uk/links/">Other Links</a></li>
              </ul>
            </li>-->
                <li class="{% if nbar == 'subscribe' %}active{% endif %}"><a href="{% url 'contact:join' %}">Subscribe</a>
                </li>
            </ul>
    
          <!--<ul class="nav navbar-nav navbar-right">
            <form class="navbar-form navbar-left" role="search" method='GET' action=''>
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search posts " name='q' value='{{ request.GET.q }}'>
                </div>
            <button type="submit" class="btn btn-default">Submit</button>
            </form>
          </ul>-->
          
            <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                    <li class='pull-right'><a href="{% url 'login' %}">Login</a></li>
                    <li class='pull-right'><a href="{% url 'register' %}">Register</a></li>
                {% else %}
                    <li class='pull-right'><a href="{% url 'logout' %}">Logout</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title%}

{% block content %}

<div class="row">
<div class="col-md-12">
   
<h1>{{ title }}
<small>
{% if instance.draft %}
<span style="color:red">Draft: </span>
{% endif %}
{{ instance.published }}
{% if instance.published > today %}
<text style="color:green;"> (Future Post - Staff Only)</text>
{% endif %}
<!--superusers menu-->
{% if request.user.is_staff or request.user.is_superuser %}
<a href="{{ request.build_absolute_uri }}edit/"> Update</a> |
<a href="{{ request.build_absolute_uri }}delete/" style="color:red;"> Delete </a>
{% endif %}
</small>
</h1>
    
{% if instance.user.get_full_name %}
<p>Author: {{ instance.user.get_full_name }}</p>
{% endif %}
    
   
<!--Title:{{ instance.title }}<br/>-->

{% if instance.image %}
<img src='{{ instance.image.url }}' class='img-responsive' /><br/>
       {% endif %}


<div class='post-detail-item'><!--references content markdown thirdparty plug-in -->
{{ instance.get_markdown }}
  </div>

<br/><!--Content:-->
      
<b>Last updated: </b>{{ instance.updated }}<br/>
<b>Created: </b>{{ instance.timestamp }}<br/>


     
<!--shares-->


<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Facebook</a>
<a href="https://twitter.com/home?status={{ instance.content|truncatechars:60|urlify }}%20@trisvandis%20{{ request.build_absolute_uri  }}">Twitter
    </a>
<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google Plus</a>
<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri  }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">Linked</a>
</div>
</div>

<div>
  <h3 class='lead'>Comments</h3>
  {% if request.user.is_authenticated %}
  <form method='POST' action='.'>{% csrf_token %}
    {{ comment_form|crispy }}
    <input type='submit' value='Post comment' class='btn btn-default'>
  </form>
  {% else %}
  <p>You must <a href="{% url 'login' %}">login</a> to comment</p>
  {% endif %}
  {% for comment in comments %}

<blockquote>
    {{ comment.content }}<br/>
    <footer>{{ comment.timestamp|timesince }} by {{ comment.user }} | <a href='{{ comment.get_absolute_url }}'>{% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1%}s{% endif %}</a> | {% endif %}<a class='comment-reply-btn' href='#'>Reply</a></footer>
   <div class='comment-reply'><!--comment reply-->
      {% for child_comment in comment.children %}
    <blockquote>
      <p>{{ child_comment.content }}</p>
      <footer>{{ child_comment.timestamp|timesince }} by {{ child_comment.user }}</footer>
    </blockquote>
    {% endfor %}
  {% if request.user.is_authenticated %}
    <form method='POST' action='.'>{% csrf_token %}
      {{ comment_form|crispy }}
    <input type='hidden' name='parent_id' value='{{ comment.id }}'>
    <input type='submit' value='Reply' class='btn btn-default'>

    </form>
 {% endif %}
   </div><!--end of comment reply-->
    

</blockquote>
  <hr/>
  
  {% endfor %}
</div>


{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}New Post | {{ block.super }}{% endblock head_title%}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}

<div class="row">


  
<div class="col-sm-6">
<h1>Preview</h1>
</div>
<div class='content-preview'>
  <h3 id='preview-title'></h3>
  <p id='preview-content'></p>
</div>

<div class="col-sm-6">
<h1>New Post</h1>



<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}

<!--{{ form.as_p }}-->
{{ form|crispy }}

<input type="submit" class= 'btn btn-default' value="Create Post" />
</form>
</div>
</div>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}
     
{% block content %}
 
 

 
  <h1>Development Blog
  
<!--superusers menu-->
    
    {% if request.user.is_staff or request.user.is_superuser %}
    <small>
        | <a href="{{ request.build_absolute_uri }}create/">Create New</a>
      </small>
    {% endif %}
  </h1>
  
  
  
  <form method='GET' action=''>
    <div class='input-group'>
      <input class='form-control' type='text' name='q' plceholders='Search posts' value='{{ request.GET.q }}'/>
      <span class='input-group-btn'>
      <!--input class='btn btn-default' type='submit' value='Search'/-->
      <button class='btn btn-default' type='submit'>Search <i class='fa fa-search'></i></button>
      </span>
    </div>
  </form>
  
 <div class="row">
    {% for obj in object_list %}
    
    <div class="col-md-12">
      <div class="thumbnail">
        {% if obj.image %}
        <img src='{{ obj.image.url }}' class='img-responsive'>
        {% endif %}
      <div class="caption post-detail-item">
        <h3>{% if obj.draft %}<text style="color:red;">Draft: {% endif %}<a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.published }}{% if obj.published > today %}<text style="color:green;"> (Future Post)</text>{% endif %}</small></h3>
            {% if obj.user.get_full_name %}
              <p>Author: {{ obj.user.get_full_name }}</p>
            {% endif %}
        <p><small>Read Time: {% if obj.read_time <= 1 %} Less than 1 min {% else %}{{ obj.read_time }} mins {% endif %}</small></p>
        <p>{{ obj.get_markdown|truncatewords_html:10 }}</p>
        
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  
  <hr/>
  </div>

{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

 <!--superusers menu-->
    
    {% if request.user.is_staff or request.user.is_superuser %}
    <small>
      <a href="{{ request.build_absolute_uri }}create/">Create New</a>
    </small>
    {% endif %}
    
    
</div>








    
{% endblock content %}